config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :conversations, only: [:index, :show] do
    resources :messages, module: :conversations, only: [:index, :new, :create, :show]
  end

  resources :inventory_reports
  resources :service_requests do
    resources :activity, module: :service_requests, only: [:new, :create]
    member do
      patch :close
      patch :reopen
      patch :make_inprogress
    end
    collection do
        get :open
        get :in_progress
    end
  end
  resources :technicians
  resources :payment_imports, only: [:index, :new, :create]

  # Twilio Webhooks
  post 'conversations/messages/reply', to: 'conversations/messages#reply'
end

app/models/technician.rb
class Technician < ActiveRecord::Base
  validates_presence_of :name, :phone_number, :email, :street, :city, :state, :zipcode

  belongs_to :user
  has_one :conversation, :dependent => :destroy

  geocoded_by :address
  after_validation :geocode

  # After creation create the conversation record so it exists
  # It's used to tie in messages sent to the Tech
  after_create :create_conversation!

  def address
    [street, city, state, zipcode].compact.join(', ')
  end

  def create_conversation!
    # Would have normally used just Conversation.create here, but choose to
    # use find_or_create_by to ensure that it would not somehow create orphan records
    Conversation.find_or_create_by(technician: self, user: self.user)
  end
end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_technician, only: [:show, :update, :edit, :destroy]

  def index
    @technician = current_user.technicians.all
  end

  def create
    @technician = current_user.technicians.build(technician_params)

    if @technician.save
      redirect_to technicians_path, notice: 'Technician has been added'
    else
      render 'new'
    end
  end

  def new
    @technician = current_user.technicians.new
  end

  def show
  end

  def edit
  end

  def update
    if @technician.update(technician_params)
      redirect_to technicians_path, notice: 'Technician has been updated'
    else
      render 'edit'
    end
  end

  def destroy
    @technician.destroy
    redirect_to technicians_path, notice: 'Technician has been deleted'
  end

  private
    def technician_params
      params.require(:technician).permit(:name, :phone_number, :email, :street, :city, :state, :zipcode)
    end

    def set_technician
      @technician = Technician.find(params[:id])
    end
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/views/technicians/_form.html.erb
<%= form_for(@technician) do |f| %>
<div class="col-sm-4">
  <% if @technician.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@technician.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @technician.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :street %>
    <%= f.text_field :street, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :state %>
    <%= f.text_field :state, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Save Technician", class: 'btn btn-primary' %>
  </div>
<% end %>
</div>

app/views/technicians/edit.html.erb
<h1>Edit Technician</h1>

<%= render 'form' %>

app/views/technicians/index.html.erb
<%= link_to "Add Technician", new_technician_path, class: 'btn btn-primary' %>
<h3>Manage Technicians</h3>
<table class="table table-bordered table-striped table-responsive">
       <thead>
         <tr>
           <th>Name</th>
           <th>Phone Number</th>
           <th>Email</th>
           <th>Address</th>
           <th>lat</th>
           <th>long</th>
           <th></th>
         </tr>
       </thead>
       <tbody>
         <% if @technician.empty? %>
           <tr>
             <td colspan="7" class="text-center">Sorry, no technicians could be found. You should <%= link_to "create a technician", new_technician_path %> to fix this</td>
           </tr>
         <% end %>
         <% @technician.each do |technician| %>
         <tr>
           <td>
             <%= technician.name %>
           </td>
           <td>
             <%= technician.phone_number %>
           </td>
           <td>
            <%= technician.email %>
           </td>
           <td>
            <%= technician.address %>
           </td>
           <td>
            <%= technician.latitude %>
           </td>
           <td>
            <%= technician.longitude %>
           </td>
           <td>
             <%= link_to edit_technician_path(technician) do %>
               <i class="fa fa-pencil-square-o fa-2x"></i>
             <% end %>
             &nbsp; &nbsp;
             <%= link_to technician_path(technician), method: :delete, data: { confirm: "Are you sure you want to delete this?" } do %>
               <i class="fa fa-trash-o fa-2x"></i>
             <% end %>

           </td>
         </tr>
         <% end %>
       </tbody>
     </table>

  <div class="row">
    <div class="col-sm-12">
      <h3>Map</h3>
      <div id='map' style='width: 800px; height: 600px;' />
    <script>
      mapboxgl.accessToken = '<%= Rails.application.secrets.mapbox_key %>';

      var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v8',
        attributionControl: false
      });
    map.setZoom(7);
    map.setCenter(["-87.544834", "33.1479767"]);
    map.addControl(new mapboxgl.Attribution({position: 'bottom-left'}));
    map.addControl(new mapboxgl.Navigation());

    map.on('load', function () {

      map.addSource("markers", {
          "type": "geojson",
          "data": {
              "type": "FeatureCollection",
              "features": [
                <% @technician.each do |technician| %>
                  {
                    "type": "Feature",
                    "geometry": {
                        "type": "Point",
                        "coordinates": [<%= technician.longitude %>, <%= technician.latitude %>] // Long then lat
                    },  "properties": {
                          "title": "<%= technician.name %>",
                          "marker-symbol": "monument",
                          "marker-size": "small"
                      }
                  },
                <% end %>
              ]
          }
      });

      map.addLayer({
          "id": "markers",
          "type": "symbol",
          "source": "markers",
          "layout": {
              "icon-image": "{marker-symbol}-15",
              "text-field": "{title}",
              "text-font": ["Open Sans Semibold", "Arial Unicode MS Bold"],
              "text-offset": [0, 0.6],
              "text-anchor": "top"
          }
      });
    });
    </script>
    </div>
  </div>

app/views/technicians/new.html.erb
<h1>New Technician</h1>

<%= render 'form' %>