config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :conversations, only: [:index, :show] do
    resources :messages, module: :conversations, only: [:index, :new, :create, :show]
  end

  resources :inventory_reports
  resources :service_requests do
    resources :activity, module: :service_requests, only: [:new, :create]
    member do
      patch :close
      patch :reopen
      patch :make_inprogress
    end
    collection do
        get :open
        get :in_progress
    end
  end
  resources :technicians
  resources :payment_imports, only: [:index, :new, :create]

  # Twilio Webhooks
  post 'conversations/messages/reply', to: 'conversations/messages#reply'
end

app/models/inventory_report.rb
class InventoryReport < ActiveRecord::Base
  validates_presence_of :technician_name, :dish_count, :cannister_count, :modem_count,
                        :radio_count, :voip_count, :trimast_count, :upgradearm_count,
                        :raven_upgrade_kit_count

end

app/controllers/inventory_reports_controller.rb
class InventoryReportsController < ApplicationController
  before_action :set_inventory_report, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @inventory_reports = InventoryReport.order("created_at DESC")
    @inventory_total = InventoryReport.select("sum(dish_count) as dish_count, sum(cannister_count) as cannister_count, sum(modem_count) as modem_count, sum(radio_count) as radio_count, sum(raven_upgrade_kit_count) as raven_upgrade_kit_count,
    sum(upgradearm_count) as upgradearm_count, sum(voip_count) as voip_count, sum(trimast_count) as trimast_count, sum(routers) as routers_count")

    authorize @inventory_reports
  end

  def new
    @inventory_report = InventoryReport.new
    authorize @inventory_report
  end

  def create
    @inventory_report = InventoryReport.create(inventory_report_params)

    if @inventory_report.save
      redirect_to inventory_reports_path, notice: "Your Inventory Report has been added"
    else
      render 'new'
    end

    authorize @inventory_report
  end

  def show
    authorize @inventory_report
  end

  def edit
    authorize @inventory_report
  end

  def update
    if @inventory_report.update(inventory_report_params)
      redirect_to @inventory_report, notice: "This report was updated!"
    else
      render 'edit'
    end
    authorize @inventory_report
  end

  def destroy
    @inventory_report.destroy
    redirect_to inventory_reports_path, notice: "That inventory report has been permanently deleted!"
    authorize @inventory_report
  end

  private

    def set_inventory_report
      @inventory_report = InventoryReport.find(params[:id])
    end

    def inventory_report_params
      params.require(:inventory_report).permit(:technician_name, :dish_count, :cannister_count, :modem_count, :radio_count, :voip_count, :trimast_count, :upgradearm_count, :raven_upgrade_kit_count, :routers, :notes)
    end
end

app/helpers/inventory_report_helper.rb
module InventoryReportHelper
end

app/views/inventory_reports/_form.html.erb
<%= simple_form_for(@inventory_report) do |f| %>
<div class="col-md-10">
  <div class="row">
    <div class="col-md-8">
      <%= f.input :technician_name %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= f.input :dish_count %>
      <%= f.input :cannister_count %>
    </div>
    <div class="col-md-4">
      <%= f.input :modem_count %>
      <%= f.input :radio_count %>
    </div>
  </div>
<div class="row">
  <div class="col-md-4">
    <%= f.input :voip_count, label: "VoIPs / ATAs Count" %>
    <%= f.input :trimast_count %>
  </div>
  <div class="col-md-4">
    <%= f.input :upgradearm_count, label: "Upgrade arms" %>
    <%= f.input :raven_upgrade_kit_count %>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <%= f.input :routers, label: 'Wireless Routers' %>
  </div>
</div>
<div class="row">
  <div class="col-md-8">

      <%= f.input :notes, as: :text, placeholder: "Enter Additional counts like HN9000 Equipment" %>
  </div>
</div>

  <%= f.button :submit, class: "btn btn-primary" %>
</div>
<% end %>

app/views/inventory_reports/edit.html.erb
<h1>Edit Inventory Report</h1>
<%= render "form" %>

app/views/inventory_reports/index.html.erb
<h1>All Inventory Reports </h1>
<% if @inventory_reports.empty? %>
<h2>Sorry there are no inventory reports yet.</h2>
<% end %>
<% if policy(InventoryReport).new? %>
<%= link_to "Add Inventory Report", new_inventory_report_path, class: "btn btn-primary" %>
<% end %>
<br><br>

<table class="table table-bordered table-striped">
  <thead>
      <tr>
        <th>Techician Name:</th>
        <th>Dishes:</th>
        <th>Cannisters:</th>
        <th>Modems:</th>
        <th>Radios:</th>
        <th>Raven Upgrade Kits:</th>
        <th>Upgrade Arms:</th>
        <th>VoIPs:</th>
        <th>Trimasts:</th>
        <th>Routers:</th>
        <th>Notes:</th>
        <th>Date</th>
        <% if policy(InventoryReport).edit? || policy(InventoryReport).destroy? %>
        <th>Actions:</th>
        <% end %>
      </tr>

  </thead>

  <tbody>
    <% @inventory_reports.each do |inventory_report| %>
      <tr>
        <td><%= inventory_report.technician_name %></td>
        <td><%= inventory_report.dish_count %></td>
        <td><%= inventory_report.cannister_count %></td>
        <td><%= inventory_report.modem_count %></td>
        <td><%= inventory_report.radio_count %></td>
        <td><%= inventory_report.raven_upgrade_kit_count %></td>
        <td><%= inventory_report.upgradearm_count %></td>
        <td><%= inventory_report.voip_count %></td>
        <td><%= inventory_report.trimast_count %></td>
        <td><%= inventory_report.routers %></td>
        <td><%= inventory_report.notes %></td>
        <td><%= local_time inventory_report.created_at %></td>
        <td>
          <%= link_to edit_inventory_report_path(inventory_report) do %>
            <i class="fa fa-pencil-square-o fa-2x"></i>
          <% end if policy(inventory_report).edit? %>
          &nbsp; &nbsp;
          <%= link_to inventory_report_path(inventory_report), method: :delete, data: { confirm: "Are you sure you want to delete this?" } do %>
            <i class="fa fa-trash-o fa-2x"></i>
          <% end if policy(inventory_report).destroy? %>
        </td>
      </tr>
    <% end %>


  <!--  <tr>
      <th></th>
      <th><%#= @inventory_reports.sum(:dish_count) %></th>
      <th><%#= @inventory_reports.sum(:cannister_count) %></th>
      <th><%#= @inventory_reports.sum(:modem_count) %></th>
      <th><%#= @inventory_reports.sum(:radio_count) %></th>
      <th><%#= @inventory_reports.sum(:raven_upgrade_kit_count) %></th>
      <th><%#= @inventory_reports.sum(:upgradearm_count) %></th>
      <th><%#= @inventory_reports.sum(:voip_count) %></th>
      <th><%#= @inventory_reports.sum(:trimast_count) %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr> -->
    <% @inventory_total.each do |total| %>
      <tr class="warning">
        <td></td>
        <td><%= total.dish_count %> dishes</td>
        <td><%= total.cannister_count %> cannisters</td>
        <td><%= total.modem_count %> modems</td>
        <td><%= total.radio_count %> radios</td>
        <td><%= total.raven_upgrade_kit_count %> raven kits</td>
        <td><%= total.upgradearm_count %> upgrade arms</td>
        <td><%= total.voip_count %> VoIPs</td>
        <td><%= total.trimast_count %> trimasts</td>
        <td><%= total.routers_count %> routers</td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/inventory_reports/new.html.erb
<h1>New Inventory Report</h1>
<p>Enter an Inventory Report below, please make sure to fill out all fields</p>
<%= render "form" %>

app/views/inventory_reports/show.html.erb
<%= @inventory_report.id %>