config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :conversations, only: [:index, :show] do
    resources :messages, module: :conversations, only: [:index, :new, :create, :show]
  end

  resources :inventory_reports
  resources :service_requests do
    resources :activity, module: :service_requests, only: [:new, :create]
    member do
      patch :close
      patch :reopen
      patch :make_inprogress
    end
    collection do
        get :open
        get :in_progress
    end
  end
  resources :technicians
  resources :payment_imports, only: [:index, :new, :create]

  # Twilio Webhooks
  post 'conversations/messages/reply', to: 'conversations/messages#reply'
end

app/models/service_request.rb
class ServiceRequest < ActiveRecord::Base
  validates_presence_of :customer_name, :address, :description
  has_many :activities
  
  scope :status, -> (status) { where(status: status) }

  def customer_phone_number
    if self.customer_phone.empty?
      "No phone number on file"
    else
      self.customer_phone
    end
  end

  def customer_email_address
    if self.customer_email.empty?
      "No email on file"
    else
      self.customer_email
    end
  end
end

app/controllers/service_requests/activity_controller.rb
class ServiceRequests::ActivityController < ApplicationController
  before_action :authenticate_user!
  before_action :set_service_request, only: [:new, :create]

  def new
    @activity = @service_request.activities.new
  end

  def create
    @activity = @service_request.activities.build(activity_params)
    @activity.user_id = current_user.id

    if @activity.save
      redirect_to service_request_path(@service_request), notice: 'Activity has been added'
    else
      redirect_to service_request_path(@service_request), alert: 'Activity could not be added. Please try again.'
    end
  end

  private
    def set_service_request
      @service_request = ServiceRequest.find(params[:service_request_id])
    end

    def activity_params
      params.require(:activity).permit(:body)
    end
end

app/controllers/service_requests_controller.rb
class ServiceRequestsController < ApplicationController
  before_action :set_service_request, except: [:index, :new, :create, :in_progress, :open]
  before_action :authenticate_user!
  def index
    @service_requests = ServiceRequest.order("created_at DESC")
  end

  def open
    @service_requests = ServiceRequest.status("open").order("created_at DESC")
    render action: :index
  end

  def in_progress
    @service_requests = ServiceRequest.status("in_progress").order("created_at DESC")
    render action: :index
  end

  def show
  end

  def edit
  end

  def update
    if @service_request.update(service_request_params)
      redirect_to @service_request, notice: "This request has been updated"
    else
      render 'edit'
    end
  end

  def new
    @service_request = ServiceRequest.new
  end

  def create
    @service_request = ServiceRequest.new(service_request_params)
    @service_request.status = "open"
    if @service_request.save
      redirect_to @service_request, notice: "Service Request has been submitted!"
    else
      render 'new'
    end
  end

  def destroy
    @service_request.destroy
    redirect_to service_requests_path, notice: "That request has been destroyed!"
  end

  def close
    #@service_request.status = "closed"
    if @service_request.update_attribute(:status, "closed")
      redirect_to @service_request, notice: "Closed service request ##{@service_request.id}"
    else
      redirect_to @service_request, notice: "An error occurred"
    end
  end

  def reopen
    if @service_request.update_attribute(:status, "open")
      redirect_to @service_request, notice: "Re-opened service request ##{@service_request.id}"
    else
      redirect_to @service_request, notice: "An error occurred"
    end
  end

  def make_inprogress
    if @service_request.update_attribute(:status, "in_progress")
      redirect_to @service_request, notice: "Marked service request ##{@service_request.id} as in-progress"
    else
      redirect_to @service_request, notice: "An error occurred"
    end
  end

  private
    def set_service_request
      @service_request = ServiceRequest.find(params[:id])
    end

    def service_request_params
      params.require(:service_request).permit(:customer_name, :customer_phone, :customer_email, :address, :apartment, :city, :state, :zipcode, :description, :status)
    end
end

app/helpers/service_requests/activity_helper.rb
module ServiceRequests::ActivityHelper
end

app/helpers/service_requests_helper.rb
module ServiceRequestsHelper
end

app/views/service_requests/_form.html.erb
<%= simple_form_for(@service_request) do |f| %>
<div class="col-md-10">
  <div class="row">
    <div class="col-md-4">
      <%= f.input :customer_name %>
      <%= f.input :customer_phone %>
      <%= f.input :customer_email %>
    </div>
    <div class="col-md-4">
      <%= f.input :address %>
      <%= f.input :apartment %>
      <%= f.input :city %>
      <%= f.input :state %>
      <%= f.input :zipcode %>
    </div>
  </div>
<div class="row">
  <div class="col-md-8">
    <%= f.input :description, as: :text, placeholder: "Please enter customer problems here", :input_html => { :rows => 7 } %>
  </div>
</div>

  <%= f.button :submit, class: "btn btn-primary" %>
</div>
<% end %>

app/views/service_requests/edit.html.erb
<h1>Edit Service Request</h1>
<%= render 'form' %>

app/views/service_requests/index.html.erb
<h1>All Service Requests </h1>
<% if @service_requests.empty? %>
<h2>There have been no service requests yet.</h2>
<% end %>
<%= link_to "Add Service Request", new_service_request_path, class: "btn btn-primary" %>
<div class="pull-right">
<%= link_to "Open Service Requests", open_service_requests_path, class: "btn btn-success" %>
<%= link_to "In Progress Service Requests", in_progress_service_requests_path, class: "btn btn-info" %>
</div>
<br><br>
<% unless @service_requests.empty? %>
<table class="table table-bordered table-striped">
  <thead>
      <tr>
        <th>ID:</th>
        <th>Status</th>
        <th>Name:</th>
        <th>Phone:</th>
        <th>Email:</th>
        <th>Address:</th>
        <th>City:</th>
        <th>State:</th>
        <th>Zipcode:</th>
        <th>Description:</th>
        <th>Submitted:</th>
        <th>Actions:</th>
      </tr>

  </thead>

  <tbody>
    <% end %>
    <% @service_requests.each do |request| %>
      <tr>
        <td><%= link_to request.id, service_request_path(request.id) %></td>
        <td><%= request.status.humanize %></td>
        <td><%= request.customer_name %></td>
        <td><%= request.customer_phone_number %></td>
        <td><%= request.customer_email_address %></td>
        <td><%= request.address %> <%= request.apartment %></td>
        <td><%= request.city %></td>
        <td><%= request.state %></td>
        <td><%= request.zipcode %></td>
        <td><%= request.description %></td>
        <td><%= local_time_ago request.created_at %></td>
        <td>
          <%= link_to edit_service_request_path(request) do %>
            <i class="fa fa-pencil-square-o fa-2x"></i> &nbsp; &nbsp;
          <% end %>
          <%= link_to service_request_path(request), method: :delete, data: { confirm: "Are you sure you want to delete this?" } do %>
            <i class="fa fa-trash-o fa-2x"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/service_requests/new.html.erb
<h1>New Service Request</h1>
<%= render 'form' %>

app/views/service_requests/show.html.erb
<h2>Service Request #<%= @service_request.id %> &nbsp;<span class="label label-default"><%= @service_request.status.humanize %></span></h2>
<hr />
<div class="row">
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Customer Information</h3>
      </div>
      <ul class="list-group">
        <li class="list-group-item"><strong>Name:</strong> <%= @service_request.customer_name %></li>
        <li class="list-group-item"><strong>Email:</strong> <%= @service_request.customer_email_address %></li>
        <li class="list-group-item"><strong>Phone:</strong> <%= @service_request.customer_phone_number %></li>
      </ul>
      <div class="panel-body">
        <address>
          <strong>Address:</strong><br />
          <%= @service_request.address %>, <% if !@service_request.apartment.empty? %>Apt <%= @service_request.apartment %><% end %><br>
          <%= @service_request.city %>, <%= @service_request.state %> <%= @service_request.zipcode %><br>
        </address>
      </div>
    </div>
  </div><!-- End col-md for customer panel -->

  <div class="col-md-8">
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">Actions</h3>
        </div>
        <div class="panel-body">

          <!-- Single button -->
          <div class="btn-group">
            <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Modify Status <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
            <% if @service_request.status == "open" %>
              <li>
                <%= link_to make_inprogress_service_request_path(@service_request), method: :patch do %>
                  Mark as In Progress
                <% end %>
              </li>
            <% end %>
            <% if @service_request.status == "closed" %>
              <li>
                <%= link_to reopen_service_request_path(@service_request), method: :patch do %>
                  Re-open Service Request
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to close_service_request_path(@service_request), method: :patch do %>
                  Close Service Request
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>

        </div>
      </div>
    </div>

    <div class="row">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title">Customer Complaint</h3>
        </div>
        <div class="panel-body">
          <%= @service_request.description %>
        </div>
      </div>
    </div>

  </div>
</div><!-- End Row For Customer / SR information -->

<hr>
<h3>Activity</h3>
<% if @service_request.activities.empty? %>
  <h4>There have been no activity on this Service Request yet.</h4>
  <p>Type below to send the first update.</p>
<% else %>
  <% @service_request.activities.includes(:user).order("created_at ASC").each do |activity| %>
    <div class="row">
      <div class="col-md-12">
        <div class="panel panel-info">

          <div class="panel-heading">
            <div class="pull-right">
            <%= local_time_ago activity.created_at %>&nbsp;<%= fa_icon 'clock-o' %>
            </div>
            <strong>Posted by:</strong> <%= activity.user.full_name %>
          </div>
          <div class="panel-body">
            <%= activity.body %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<% unless @service_request.status == "closed" %>
  <div class="row">
    <div class="col-sm-12">
      <%= form_for (@service_request.activities.new), url: service_request_activity_index_path(@service_request) do |f| %>
        <div class="form-group">
          <%= f.text_area :body, class: 'form-control', placeholder: 'Type an update to send' %>
        </div>
          <%= f.submit 'Add Update', class: 'btn btn-primary' %>
      <% end %>

    </div>
  </div>
<% end %>