config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users

  resources :conversations, only: [:index, :show] do
    resources :messages, module: :conversations, only: [:index, :new, :create, :show]
  end

  resources :inventory_reports
  resources :service_requests do
    resources :activity, module: :service_requests, only: [:new, :create]
    member do
      patch :close
      patch :reopen
      patch :make_inprogress
    end
    collection do
        get :open
        get :in_progress
    end
  end
  resources :technicians
  resources :payment_imports, only: [:index, :new, :create]

  # Twilio Webhooks
  post 'conversations/messages/reply', to: 'conversations/messages#reply'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  belongs_to :service_request

  validates_presence_of :body
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :user
  belongs_to :technician

  has_many :messages
end

app/models/inventory_report.rb
class InventoryReport < ActiveRecord::Base
  validates_presence_of :technician_name, :dish_count, :cannister_count, :modem_count,
                        :radio_count, :voip_count, :trimast_count, :upgradearm_count,
                        :raven_upgrade_kit_count

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation

  validates_presence_of :body

end

app/models/service_request.rb
class ServiceRequest < ActiveRecord::Base
  validates_presence_of :customer_name, :address, :description
  has_many :activities
  
  scope :status, -> (status) { where(status: status) }

  def customer_phone_number
    if self.customer_phone.empty?
      "No phone number on file"
    else
      self.customer_phone
    end
  end

  def customer_email_address
    if self.customer_email.empty?
      "No email on file"
    else
      self.customer_email
    end
  end
end

app/models/sms.rb
class SMS
  def initialize(to_phone_number)
    @to_phone_number = to_phone_number
  end

  def client
    Twilio::REST::Client.new Rails.application.secrets.twilio_account_sid, Rails.application.secrets.twilio_token
  end

  def send(body)
    client.account.messages.create(
      :messaging_service_sid => Rails.application.secrets.twilio_messaging_service_sid,
      :to => @to_phone_number,
      :body => body
    )
  end
end

app/models/technician.rb
class Technician < ActiveRecord::Base
  validates_presence_of :name, :phone_number, :email, :street, :city, :state, :zipcode

  belongs_to :user
  has_one :conversation, :dependent => :destroy

  geocoded_by :address
  after_validation :geocode

  # After creation create the conversation record so it exists
  # It's used to tie in messages sent to the Tech
  after_create :create_conversation!

  def address
    [street, city, state, zipcode].compact.join(', ')
  end

  def create_conversation!
    # Would have normally used just Conversation.create here, but choose to
    # use find_or_create_by to ensure that it would not somehow create orphan records
    Conversation.find_or_create_by(technician: self, user: self.user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  has_many :activities
  has_many :conversations
  has_many :messages, through: :conversations
  has_many :technicians

  def full_name
    self.first_name + " " + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Lock things down with Pundit
  include Pundit


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) {
        |u| u.permit(:email, :password, :password_confirmation, :remember_me, :first_name, :last_name)
      }
      devise_parameter_sanitizer.for(:account_update) {
        |u| u.permit(:email, :password, :password_confirmation, :current_password, :first_name, :last_name)
      }
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @conversations = current_user.conversations.includes(:technician).all
  end

  def show
    @conversation = current_user.conversations.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/payment_imports_controller.rb
class PaymentImportsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def create
    raise params[:file]
  end

end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_technician, only: [:show, :update, :edit, :destroy]

  def index
    @technician = current_user.technicians.all
  end

  def create
    @technician = current_user.technicians.build(technician_params)

    if @technician.save
      redirect_to technicians_path, notice: 'Technician has been added'
    else
      render 'new'
    end
  end

  def new
    @technician = current_user.technicians.new
  end

  def show
  end

  def edit
  end

  def update
    if @technician.update(technician_params)
      redirect_to technicians_path, notice: 'Technician has been updated'
    else
      render 'edit'
    end
  end

  def destroy
    @technician.destroy
    redirect_to technicians_path, notice: 'Technician has been deleted'
  end

  private
    def technician_params
      params.require(:technician).permit(:name, :phone_number, :email, :street, :city, :state, :zipcode)
    end

    def set_technician
      @technician = Technician.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
   { success: "alert-success", error: "alert-danger", alert: "alert-danger", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
 end

 def flash_messages(opts = {})
   flash.each do |msg_type, message|
     concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
       concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
         concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
         concat content_tag(:span, 'Close', class: 'sr-only')
       end)
       concat message
     end)
   end
   nil
 end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/inventory_report_helper.rb
module InventoryReportHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payment_imports_helper.rb
module PaymentImportsHelper
end

app/helpers/service_requests_helper.rb
module ServiceRequestsHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "{ClearManagement}", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if user_signed_in? %>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to inventory_reports_path do %>
              <%= fa_icon 'file-o fa-fw', text: 'Inventory Count' %>
          <% end %>
        </li>
        <!--
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-file-o fa-fw"></i> Inventory Reports <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to inventory_reports_path do %>
                  <i class="fa fa-files-o fa-fw"></i> All Reports
                <% end %>
              </li>
              <li>
                <%= link_to new_inventory_report_path do %>
                  <i class="fa fa-plus-square-o fa-fw"></i>  New Inventory Report
                <% end %>
              </li>
            </ul>
          </li>
        -->
        <!--
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-clock-o fa-fw"></i> Timecard <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-list-alt fa-fw"></i> Timesheets
                <% end %>
              </li>
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-plus-square-o fa-fw"></i>  Add Time
                <% end %>
              </li>
            </ul>
          </li>
        -->
        <!--
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-money fa-fw"></i> Paysheets <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-list-alt fa-fw"></i> Current Paysheets
                <% end %>
              </li>
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-search fa-fw"></i>  Search Paysheets
                <% end %>
              </li>
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-plus-square-o fa-fw"></i>  Add Paysheet
                <% end %>
              </li>
            </ul>
          </li>
        -->

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-support fa-fw"></i> Service Requests <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to service_requests_path do %>
                  <i class="fa fa-list fa-fw"></i> All Requests
                <% end %>
              </li>
              <li>
                <%= link_to new_service_request_path do %>
                  <i class="fa fa-plus-square-o fa-fw"></i>  New Service Request
                <% end %>
              </li>
            </ul>
          </li>
          <li>
            <%= link_to conversations_path do %>
                <%= fa_icon 'comments-o fa-fw', text: 'Conversations' %>
            <% end %>
          </li>
      </ul>
    <% end %>
      <!--<form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search account">
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user fa-fw"></i> <%= current_user.full_name %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to technicians_path do %>
                  <i class="fa fa-users fa-fw"></i> Manage Technicians
                <% end %>
              </li>
              <!--
              <li>
                <%= link_to new_payment_import_path do %>
                  <i class="fa fa-university fa-fw"></i> Import ACH Payments
                <% end %>
              </li>
              <li>
                <%= link_to root_path do %>
                  <i class="fa fa-files-o fa-fw"></i> Reports
                <% end %>
              </li>
            -->
              <li class="divider"></li>
              <li>
                <%= link_to edit_user_registration_path do %>
                    <i class="fa fa-cog fa-fw"></i> Manage Account
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                      <i class="fa fa-sign-out fa-fw"></i>   Sign Out
                <% end %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to new_user_session_path do %>
              <i class="fa fa-sign-in fa-fw"></i> Sign In
            <% end %>
          </li>
          <li>
            <li>
              <%= link_to new_user_registration_path do %>
                <i class="fa fa-user-plus fa-fw"></i> Sign Up
              <% end %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>ClearManagement</title>
  <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.17.0/mapbox-gl.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.17.0/mapbox-gl.css' rel='stylesheet'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render 'layouts/header' %>

  <div class="container-fluid">
    <%= flash_messages %>
    <%= yield %>
  </div>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<ul>
  <li><strong>Payment Tracking</strong></li>
  <li>CSV import from work software of payments received for jobs done.</li>
  <li>When the employees are checking the paysheets they search FSOs to see if the job has been paid and they look at the amount paid to determine the pay.</li>
  <li>Thinking this should be called ReceivedPayments on the back end to prevent conflicts</li>
  <li></li>
  <li></li>
  <li></li>
</ul>